### ISSUE TITLE
Failure of Executing HLATyping Command Line

### ISSUE THREAD

**Issue by KunFang93** [XSLiuLab/Seq2Neo#2]
Hi,

Thanks for offering this comprehensive tool. I have successfully run docker container with the following command
```
docker run -it -v /data/kun/software/Seq2Neo/resource_files/:/home/resource_files -d --name seq2neo liuxslab/seq2neo:latest /bin/bash
```

When I tried to run the following command:
```
seq2neo whole --ref /home/resource_files/ref_genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa --normal-dna Patient353_Normal_dna_1.fastq.gz Patient353_Normal_dna_2.fastq.gz --tumor-dna Patient353_T1_Tumor_dna_1.fastq.gz Patient353_T1_Tumor_dna_2.fastq.gz --tumor-rna Patient353_T1_Tumor_rna_1.fastq.gz Patient353_T1_Tumor_rna_2.fastq.gz --normal-name Patient353_Normal --tumor-name Patient353_T1_Tumor --known-site-dir /home/resource_files/bqsr_resource/ --mutect2-dataset-dir /home/resource_files/mutect2_resource/ --annovar-db-dir /home/seq2neo/biosoft/annovar/humandb/ --genome-lib-dir /home/resource_files/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/ --agfusion-db /home/resource_files/agfusion.homo_sapiens.95.db --out /home/resource_files/results/test/ --len 8 9 10 11 --threadN 20 --java-options '"-Xmx40G"' --hlahd-dir /home/seq2neo/biosoft/hlahd.1.4.0
```

I met with this error:
```
Executing Normal Fastp Command Line
Executing HLATyping Command Line
Traceback (most recent call last):
  File "/home/seq2neo/miniconda3/envs/Seq2Neo/bin/seq2neo", line 33, in <module>
    sys.exit(load_entry_point('Seq2Neo==1.1', 'console_scripts', 'seq2neo')())
  File "/home/seq2neo/miniconda3/envs/Seq2Neo/lib/python3.7/site-packages/seq2neo/main.py", line 13, in main
    args[0].func.main(args[1])
  File "/home/seq2neo/miniconda3/envs/Seq2Neo/lib/python3.7/site-packages/seq2neo/model/whole.py", line 23, in main
    toBAM_dna_normal(args, tmpPATH, resultsPATH)
  File "/home/seq2neo/miniconda3/envs/Seq2Neo/lib/python3.7/site-packages/seq2neo/lib/toBAM.py", line 12, in toBAM_dna_normal
    normal_sorted_bam = fastq_part_normal(args, tmpPATH, resultsPATH)
  File "/home/seq2neo/miniconda3/envs/Seq2Neo/lib/python3.7/site-packages/seq2neo/lib/toBAM.py", line 121, in fastq_part_normal
    hlahd_cmd()
  File "/home/seq2neo/miniconda3/envs/Seq2Neo/lib/python3.7/site-packages/Bio/Application/__init__.py", line 569, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 127 from 'hlahd.sh -t 20 -m 100 -f /home/seq2neo/biosoft/hlahd.1.4.0/freq_data /home/resource_files/results/test/tmp/normal_1_qc.fastq /home/resource_files/results/test/tmp/normal_2_qc.fastq /home/seq2neo/biosoft/hlahd.1.4.0/HLA_gene.split.txt /home/seq2neo/biosoft/hlahd.1.4.0/dictionary Patient353_T1_Tumor /home/resource_files/results/test/tmp', message '64163942 reads; of these:'
```

I wondered if there is a way to solve this issue? Thanks for your time and help in advance.

Best,
Kun

**Comment by KunFang93** [comment]
The problem is caused by uninstalled hlahd in docker image. Install the hlahd in the container will solve the problem.

**Comment by diaokx** [comment]
Sorry for that, the hlahd in docker image isn't install, I will repair soon.
